temporalGrpcAddress: {{ default .Env.TEMPORAL_ADDRESS "127.0.0.1:7233" }}
port: {{ default .Env.TEMPORAL_UI_PORT "8080" }}
uiRootPath: {{ default .Env.TEMPORAL_UI_ROOT_PATH "/" }}
enableUi: {{ default .Env.TEMPORAL_UI_ENABLED "true" }}
enableOpenApi: {{ default .Env.TEMPORAL_OPENAPI_ENABLED "true" }}
cors:
  allowOrigins:
    # override framework's default that allows all origins "*"
    - {{ default .Env.TEMPORAL_CORS_ORIGINS "http://localhost:8080" }}
auth:
    enabled: {{ default .Env.TEMPORAL_AUTH_ENABLED "false" }}
    providers:
    - label: {{ default .Env.TEMPORAL_AUTH_LABEL "sso" }}
      type: {{ default .Env.TEMPORAL_AUTH_TYPE "oidc" }}
      providerUrl: {{ .Env.TEMPORAL_AUTH_PROVIDER_URL }}
      clientId: {{ .Env.TEMPORAL_AUTH_CLIENT_ID }}
      clientSecret: {{ .Env.TEMPORAL_AUTH_CLIENT_SECRET }}
      callbackUrl: {{ .Env.TEMPORAL_AUTH_CALLBACK_URL }}
      scopes:
        - openid
        - profile
        - email
      audience:
      passIdToken: false
